### ISSUE TITLE
Comparison tools

### ISSUE THREAD

**Issue by fpompermaier** [odpi/bi-ai#2]
I saw that only Jupyter and Zeppelin will be considered. SInce here you're talking about BI why not considering also Apache Superset [1]? 

[1] https://superset.incubator.apache.org/

**Comment by cupidchan** [comment]
Hello Flavio, the whitepaper was done 2 years ago and the group thinks Jupyter and Zeppelin are representative enough, at least at that time. We keep working on new existing project. For example, one suggestion for 2020 is how to connect AI into BI platform programmatically. Please let me know if you are interested so that I can include you in the future conversation. I can also add you to the BI & AI mailing list. Just let me know which email should I use.

Regards,
Cupid



On Jan 29, 2020, at 3:58 AM, Flavio Pompermaier <notifications@github.com<mailto:notifications@github.com>> wrote:


I saw that only Jupyter and Zeppelin will be considered. SInce here you're talking about BI why not considering also Apache Superset [1]?

[1] https://superset.incubator.apache.org/<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsuperset.incubator.apache.org%2F&data=02%7C01%7C%7C9c05748c07fe4901a03608d7a49976b7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637158851331918729&sdata=eTHOyrbEcVewqshR0tm4zVcUVahHqhBfuIQg97%2FMP1Q%3D&reserved=0>

**Comment by fpompermaier** [comment]
Just wwrite me in private to pompermaier@okkam.it
